### ISSUE TITLE
Incorrect CFrame encoding

### ISSUE THREAD

**Issue by HiddenKaiser** [cloudfoundry/lager#117]
When passing a cframe, (in my case specifically a CFrame generated from a quaternion), the cframe is encoded incorrectly and provides undesired behavior.

Here's the code that generates the CFrame for reference:
```lua
-- EgoMoose's implementation of Quaternion.FromToRotation in lua
function HF.getRotationBetween(u, v, axis)
	local dot, uxv = u:Dot(v), u:Cross(v)
	if (dot < -0.99999) then return CFrame.fromAxisAngle(axis, math.pi) end
	return CFrame.new(0, 0, 0, uxv.x, uxv.y, uxv.z, 1 + dot)
end
```

Gif of undesired behavior:
https://gyazo.com/ab3245f5b6cd3a6e86a77d672423ded0

**Comment by winkingturtle-vmw** [comment]
@HiddenKaiser I am not clear how your issue is related to the lager library. I am going to close this ticket. If you feel like it's relevant, please open a new issue with reproduction steps.
