### ISSUE TITLE
Make slog Handler backwards compatible when logging custom errors

### ISSUE THREAD

**Issue by ten4o** [cloudfoundry/lager#126]
### Current behavior

When using slog Handler to log custom errors, the error is not converted to string and is not logged correctly.
Simple example to reproduce the problem:
```
package main

import (
	"fmt"
	"log/slog"
	"os"

	"code.cloudfoundry.org/lager/v3"
)

type CustomError struct {
	error
	statusCode int
}

func NewCustomError(err error, statusCode int) error {
	return &CustomError{
		error:      err,
		statusCode: statusCode,
	}
}

func main() {
	lagerLog := lager.NewLogger("component")
	lagerLog.RegisterSink(lager.NewWriterSink(os.Stdout, lager.DEBUG))
	err := NewCustomError(fmt.Errorf("error message"), 401)

	lagerLog.Error("this works", err)

	slogLog := slog.New(lager.NewHandler(lagerLog))
	slogLog.Error("this does not work", "error", err)
}
```
This behaviour is not backwards compatible as for parameters of type `error` [error.Error() is called in lager.Error()](https://github.com/cloudfoundry/lager/blob/main/logger.go#L143) but not in the slog Handler.

### Desired behavior

The desired behaviour is to call `Error()` for parameters of type `error` in the slog Handler.

### Affected Version

v3.0.3

**Comment by geofffranks** [comment]
Fixed via #127. Sorry for the delay!
