### ISSUE TITLE
Adopt OpenTracing standard

### ISSUE THREAD

**Issue by tedsuo** [cloudfoundry/lager#18]
In order to add trace serialization and session completion, we are moving to adopt the OpenTracing standard. The proposal can be found here:

https://docs.google.com/document/d/1jK1_gZ1PYaVPI565ObtN5rcNcFGTlOpX56-eFeD5sjU/edit?usp=sharing

Please comment on the document, or discuss here if you have any questions or concerns.

**Comment by emalm** [comment]
Closing this out as stale, although fwiw I'm still generally interested in these ideas.
