### ISSUE TITLE
How to format log timestamp?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/lager#30]
logger now just output timestamp, how to format the timestamp string to a human readable time string , like "2017-09-07 15:00:00 234"?

**Comment by emalm** [comment]
Hi, @qibobo,

There's no explicit configuration that changes lager to record the timestamp in something more human-readable, such as [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601), but you could create a new implementation of [the `Sink` interface](https://github.com/cloudfoundry/lager/blob/master/writer_sink.go) that does so.

Best,
Eric, CF Diego PM
