### ISSUE TITLE
Please add semver tags

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/lager#31]
dep/vendor tooling understands semver tagging at this point. Consuming lager as a library, I would like a specific tag with semantic meaning.

**Comment by emalm** [comment]
Hi, @cholick, that sounds pretty reasonable to me, but I'll also discuss it with the rest of the Diego team. If we do add the semver tag, would you be ok with a `v1.0.0` at the current head of master (https://github.com/cloudfoundry/lager/commit/0bfa98e49e7a976af91e918d47978f07c00b081f)?

Thanks,
Eric, CF Diego PM

**Comment by cholick** [comment]
Sure, 1.0 at current head makes sense to me.

Thanks!

**Comment by emalm** [comment]
Also, /cc @jvshahid for his consideration.

**Comment by emalm** [comment]
@cholick : https://github.com/cloudfoundry/lager/tree/v1.0.0 🎉 😀
