### ISSUE TITLE
Certificate signed by unknown authority when trying to download dependency using go get

### ISSUE THREAD

**Issue by vwatinteg** [cloudfoundry/lager#46]
Using go get in my repo produces this error message

package code.cloudfoundry.org/lager: unrecognized import path "code.cloudfoundry.org/lager": https fetch: Get "https://code.cloudfoundry.org/lager?go-get=1": x509: certificate signed by unknown authority

**Comment by vwatinteg** [comment]
needed to update machine certs

**Comment by vwatinteg** [comment]
Sorry, user error, still seeing the same issue.

**Comment by aminjam** [comment]
Are you still seeing this issue? I know that there was an error with the cert that was fixed a few weeks back.

**Comment by vwatinteg** [comment]
I just ran go get again on my repo and I don't see the issue anymore
