### ISSUE TITLE
Only valuePatterns can be configured, not keyPatterns

### ISSUE THREAD

**Issue by lyesbit** [cloudfoundry/lager#48]
**Context**
With this [PR](https://github.com/cloudfoundry/lager/pull/38) it is now possible to make the redactSink configurable and pass it some valuePatterns.

**Question/Problem**
Why did you only make the valuePatterns configurable and not the keyPatterns ? What if you don't know the pattern of the values that have to be matched/redacted but only the keys ?

**Comment by MarcPaquette** [comment]
Hi @lyesbit,
Is this question still outstanding for you?

**Comment by lyesbit** [comment]
nope
