### ISSUE TITLE
updating Ginkgo to version 2

### ISSUE THREAD

**Issue by Zoreo** [cloudfoundry/lager#56]
Hello, 

We are trying to update our tests to use [ginkgo/v2](https://github.com/onsi/ginkgo/releases), however that isn't possible since the [loggers](https://github.com/cloudfoundry/lager/blob/2c3a201cafc638f94e5acc49892cf537fbc8002b/lagertest/test_sink.go#L34) that we are using are still importing v1 and so we are getting an error similar to [this](https://github.com/onsi/ginkgo/issues/875) one (basically, the two versions of Ginkgo collide and the tests are breaking). Would it be possible for you to update the Ginkgo version to v2?

**Comment by KevinJCross** [comment]
Ive created a fork to do this becuase the v1 an v2 dont work together and the lager project is not actively maintained.
https://github.com/KevinJCross/lager
